-- Exploratory Data Analysis

select * 
from railway_cleaned;
-- A) Basic dataset exploration

# 1) Total Number of Journey

SELECT count(*) as total_journeys
FROM railway_cleaned;

# 2) Number of Unique Departure Station
SELECT COUNT(DISTINCT `Departure Station`) as unique_departure_station
FROM railway_cleaned
;

# 3) Number of unique arrival destinations
SELECT COUNT(DISTINCT `Arrival Destination`)
FROM railway_cleaned;

# 4) Maximum,Minimum and Average Ticket Price
SELECT MAX(`Price(GBP)`) as max_price,
MIN(`Price(GBP)`) as min_price,
Round(AVG(`Price(GBP)`),2) as avg_price
From railway_cleaned
WHERE `Price(GBP)` IS NOT NULL
;
# 5) Number of Unique Ticket Types

SELECT COUNT(DISTINCT `Ticket Type`) as unique_types
FROM railway_cleaned
;

-- B)What people are buying?

# 1) Total Number of journey for Ticket class

SELECT `Ticket Class`,
COUNT(`Ticket Class`) as number_of_tickets
FROM railway_cleaned
GROUP BY `Ticket Class`
ORDER BY number_of_tickets DESC;

# 2) Total Number of journey by Ticket Type

SELECT `Ticket Type`,
COUNT(`Ticket Type`) as number_of_people
FROM railway_cleaned
GROUP BY `Ticket Type`
ORDER by number_of_people DESC;

# 3) Total Number of journey by Purchase Type

SELECT `Purchase Type`,
COUNT(`Purchase Type`) as number_of_people
FROM railway_cleaned
GROUP BY `Purchase Type`
ORDER by number_of_people DESC;

# 4) Total Number of journey by Payment Method

SELECT `Payment Method`,
COUNT(`Payment Method`) as number_of_people
FROM railway_cleaned
GROUP BY `Payment Method`
ORDER by number_of_people DESC;

# 5) Railcard

SELECT `Railcard`,
COUNT(`Railcard`) as number_of_people
FROM railway_cleaned
GROUP BY `Railcard`
ORDER BY number_of_people DESC
;

-- c) Revenue Ticket Types

# 1) Total number of revenue generated by each ticket type

select `Ticket Type`, 
COUNT(`Ticket Type`) as Number_of_Tickets,
SUM(`Price(GBP)`) as `Total Revenue`,
ROUND(AVG(`Price(GBP)`),2) as `Average Price`
FROM railway_cleaned
GROUP BY `Ticket Type`
ORDER BY `Total Revenue` DESC
;

-- d) Standard vs first class

WITH try_total AS
(SELECT `Ticket Class`, 
COUNT(`Ticket Class`) as total_tickets, 
ROUND(AVG(`Price(GBP)`),2) as avg_price,
MIN(`Price(GBP)`) as min_price,
MAX(`Price(GBP)`) as max_price,
SUM(`Price(GBP)`) as revenue
FROM railway_cleaned
GROUP BY `Ticket Class`)
SELECT *,
SUM(`revenue`) over(ORDER BY `Ticket Class`) as Rolling_total
FROM try_total;


-- e) Find the busiest routes

# 1) Finding the top 10 most frequently travelled routes

WITH routes_details as
(SELECT 
CONCAT(`Departure Station` ,' ','->' ,' ',`Arrival Destination`) as Routes
FROM railway_cleaned
)
SELECT *, 
COUNT(routes) as Travelled_frequency
FROM routes_details
GROUP BY routes
ORDER BY Travelled_frequency DESC
LIMIT 10
;

-- f) Finding the most expensive routes

# 1) Find 10 routes with the highest average prices (Routes with atleast 10 journey)

WITH routes_details as
(SELECT `Price(GBP)`,
CONCAT(`Departure Station` ,' ','->' ,' ',`Arrival Destination`) as Routes
FROM railway_cleaned
)
SELECT 
Routes,
COUNT(routes) as Travelled_frequency,
ROUND(AVG(`Price(GBP)`),2) as Average_Price
FROM routes_details
GROUP BY Routes
HAVING Travelled_frequency >= 10
ORDER BY Average_Price DESC
LIMIT 10
;

-- g) Railway Reliability

SELECT `Journey Status`,
COUNT(`Journey Status`) as Number_of_Journeys,
CASE
	WHEN `Journey Status` = 'Delayed' THEN ROUND(COUNT(`Journey Status`) * 100/sum(count(*)) over(),2)
	WHEN `Journey Status` = 'On-Time' THEN ROUND(COUNT(`Journey Status`) * 100/sum(count(*)) over(),2)
    WHEN `Journey Status` = 'Cancelled' THEN ROUND(COUNT(`Journey Status`) * 100/sum(count(*)) over(),2)
END AS Percentage
FROM railway_cleaned
GROUP BY `Journey Status`
ORDER BY Percentage DESC
;

-- h) What causes delays?

SELECT `Reason for Delay`,
COUNT(`Reason for Delay`) as `Number of Delays`,
ROUND((COUNT(`Reason for Delay`)*100/sum(count(*))over()),2) as Percentage_delay
FROM railway_cleaned
WHERE `Journey Status` = 'Delayed'
GROUP BY `Reason for Delay`
ORDER BY Percentage_delay DESC
;

-- i) Delay vs Ticket Class



SELECT `Ticket Class`,
COUNT(`Ticket Class`) as `Total Journey`,
SUM(
CASE 
WHEN `Journey Status` = 'Delayed' THEN 1 ELSE 0
END
) as `Delayed Journeys`,
ROUND(
SUM(
CASE 
WHEN `Journey Status` = 'Delayed' THEN 1
ELSE 0
END
) * 100.0 / COUNT(*),2

) AS 'Delay rate'
FROM railway_cleaned
GROUP BY `Ticket Class`;

-- j) Delays vs Refund
# 1) Find Refund Rate for each journey status

SELECT * 
FROM railway_cleaned;

SELECT `Journey Status`,
COUNT(`Journey Status`) as `Total Journeys`,
SUM(`Refund Request`) as `Refund Request`,
ROUND(SUM(`Refund Request`) * (100) / COUNT(`Journey Status`),2) as `Refund Rate(%)`
FROM railway_cleaned
WHERE `Journey Status` != 'On-Time'
GROUP BY `Journey Status`
ORDER BY `Refund Rate(%)` DESC
;


-- k) Does buying earlier mean cheaper tickets?

SELECT * FROM
railway_cleaned;

with earlier_cheaper as
(SELECT `Date of Purchase`,
`Date of Journey`
,DATEDIFF(`Date of Journey` , `Date of Purchase`)
,`Price(GBP)`,
CASE 
	WHEN (DATEDIFF(`Date of Journey` , `Date of Purchase`)) <= 3 THEN '0-3 days'
    WHEN (DATEDIFF(`Date of Journey` , `Date of Purchase`)) BETWEEN 4 AND 7 THEN '4-7 days'
	WHEN (DATEDIFF(`Date of Journey` , `Date of Purchase`)) BETWEEN 8 AND 14 THEN '8-14 days'
    WHEN (DATEDIFF(`Date of Journey` , `Date of Purchase`)) BETWEEN 15 AND 30 THEN '15-30 days'
    WHEN (DATEDIFF(`Date of Journey` , `Date of Purchase`)) > 30 THEN '30+ Days'
END as `Booking Window`
FROM railway_cleaned
)
SELECT `Booking Window`,
COUNT(`Booking Window`) as `Number of Tickets`,
ROUND(AVG(`Price(GBP)`),2) as `Average Price`
FROM earlier_cheaper
GROUP BY `Booking Window`
ORDER BY `Average Price`
;



-- l) Final challange

# 1) Which route generates the most revenue?

SELECT 
CONCAT(`Departure Station` ,' ','->' ,' ',`Arrival Destination`) as Routes,
SUM(`Price(GBP)`) as `total_revenue(GBP)`
FROM railway_cleaned
GROUP BY Routes
ORDER BY `total_revenue(GBP)` DESC;


# 2) Which ticket type has the highest average price but isn't necessarily the highest-selling?

SELECT `Ticket Type`,
ROUND(AVG(`Price(GBP)`),2) as avg_price,
COUNT(`Ticket Type`) as quantity_sold
FROM railway_cleaned
GROUP BY `Ticket Type`
ORDER BY avg_price DESC;

# 3) Which delay reason has the highest refund-request rate?

SELECT `Reason for Delay`
,SUM(`Refund Request`) as Refund_Request
,SUM(`Refund Request`) *100 / COUNT(`Refund Request`) as `Refund_Rate(%)`
FROM railway_cleaned
WHERE `Reason for Delay` !=""
AND `Journey Status` != 'On-Time'
GROUP BY `Reason for Delay`
ORDER BY `Refund_Rate(%)` DESC
;




# 4) Which month has the most journeys and which month generates the most revenue?

SELECT
MONTH(`Date of Journey`) as month_number,
MONTHNAME(`Date of Journey`) AS month_name, 
COUNT(`Date of Journey`) as total_journey,
SUM(`Price(GBP)`) as revenue_month
FROM railway_cleaned
GROUP BY month_name,month_number
ORDER BY total_journey DESC;

SELECT 
substring_index(substring_index(`Date of Journey`,'-',2),'-',-1) as month_index,
SUM(`Price(GBP)`) as revenue_month
FROM railway_cleaned
GROUP BY month_index
ORDER by revenue_month DESC;








